### ISSUE TITLE
Add support for Vivliostyle

### ISSUE THREAD

**Issue by MurakamiShinyu** [zopyx/print-css-rocks#14]
The information in https://github.com/zopyx/print-css-rocks/blob/master/web/content/tools.rst#versatype-converter-formerly-known-as-vivliostyle-converter is old.

New Vivliostyle information is below:

Vivliostyle
-----------

* Current version:
    *  [Vivliostyle CLI](https://github.com/vivliostyle/vivliostyle-cli) 3.4
    *  [Vivliostyle.js](https://github.com/vivliostyle/vivliostyle.js) 2.8
* Website: https://vivliostyle.org
* Pricing: free, open-source
* CSS Compliance: https://docs.vivliostyle.org/#/supported-css-features
* Sample documents: https://vivliostyle.org/samples/
* Supported PDF profiles: 
    * PDF/X: https://docs.vivliostyle.org/#/vivliostyle-cli#generate-pdf-for-print-pdfx-1a-format

------

Please add support for Vivliostyle to print-css.rocks :-)

See some test results with Vivliostyle:

* named-pages: https://vivliostyle.org/viewer/#src=https://github.com/zopyx/print-css-rocks/blob/master/lessons/lesson-named-pages/index.html
* blank-pages: https://vivliostyle.org/viewer/#src=https://github.com/zopyx/print-css-rocks/blob/master/lessons/lesson-blank-pages/index.html
* cross-references: https://vivliostyle.org/viewer/#src=https://github.com/zopyx/print-css-rocks/blob/master/lessons/lesson-cross-references/index.html
* mathml-torture-test: https://vivliostyle.org/viewer/#src=https://github.com/zopyx/print-css-rocks/blob/master/lessons/lesson-mathml-torture-test/index.html

**Comment by zopyx** [comment]
I added  VS to the tools section.
I will add VS and update print-css.rocks with VS support later this year during with my manual major update.

**Comment by MurakamiShinyu** [comment]
@zopyx
Thanks.
Vivliostyle's current version is now:

*  [Vivliostyle CLI](https://github.com/vivliostyle/vivliostyle-cli) 3.5.1
*  [Vivliostyle.js](https://github.com/vivliostyle/vivliostyle.js) 2.8.1

**Comment by MurakamiShinyu** [comment]
@zopyx Thanks for testing Vivliostyle. The test page https://beta.print-css.rocks/lessons helps to know problems that we have to resolve.

Here are some comments on each issue:

### Footnotes

Vivliostyle supports footnotes, but has the following issue:

- https://github.com/vivliostyle/vivliostyle.js/issues/723
  - Current footnote implementation in vivliostyle.js requires the author to define explicitly the footnote counter in the stylesheet.

### Hyphenation

Vivliostyle supports hyphenation depending on the Chromium browser engine, and has problem on non-macOS platforms. See the issue:

- https://github.com/vivliostyle/vivliostyle.js/issues/569
  - Hyphenation is available on macOS, but on other platforms it is not available with Puppeteer (with headless Chrome/Chromium) that Vivliostyle CLI uses.
  - See also Puppeteer's issue https://github.com/puppeteer/puppeteer/issues/6840

### Running elements

Not yet supported. Issue: https://github.com/vivliostyle/vivliostyle.js/issues/424

### PDF bookmarks

[CSS GCPM Bookmarks](https://www.w3.org/TR/css-gcpm-3/#bookmarks) is not yet supported. Issue: https://github.com/vivliostyle/vivliostyle.js/issues/590

FYI, Vivliostyle CLI supports generating PDF bookmarks in another way. See [Vivliostyle CLI User Guide - Generate PDF Bookmarks](https://docs.vivliostyle.org/#/vivliostyle-cli#generate-pdf-bookmarks).

### Named pages

Vivliostyle supports footnotes, but has limitation that cannot change page size/orientation in the output PDF. Issue: https://github.com/vivliostyle/vivliostyle.js/issues/751

### CMYK

Not yet supported. Issue: https://github.com/vivliostyle/vivliostyle.js/issues/430

### Grid

Not yet supported. Issue: https://github.com/vivliostyle/vivliostyle.js/issues/539

### Ligatures

`font-variant-ligatures: none` is not yet supported. Issue: https://github.com/vivliostyle/vivliostyle.js/issues/592

### MathML native

Vivliostyle supports MathML using MathJax, but there have been issues:

- https://github.com/vivliostyle/vivliostyle.js/pull/753
- https://github.com/vivliostyle/vivliostyle.js/issues/750

**Comment by zopyx** [comment]
Closing the issue. Support for VS exists as beta. The beta will replace the current release some time later (also waiting for a new Weasyprint release with their new backend).

**Comment by MurakamiShinyu** [comment]
@zopyx 

Vivliostyle's current version is now:

- Vivliostyle CLI 4.1.0 - See https://github.com/vivliostyle/vivliostyle-cli/blob/main/CHANGELOG.md
- Vivliostyle.js 2.9.1 - See https://github.com/vivliostyle/vivliostyle.js/blob/master/CHANGELOG.md
