### ISSUE TITLE
Named strings examples

### ISSUE THREAD

**Issue by MurakamiShinyu** [zopyx/print-css-rocks#16]
Do you have a plan to add [Named strings](https://www.w3.org/TR/css-gcpm-3/#named-strings) examples to your site?

I think this is a very basic feature to generate running headers on CSS Paged Media. Unlike running elements, it can only treat plain text for a running header content, but it is very useful to be able to copy strings from any HTML element content or attribute value.

FYI, I made some examples to test Vivliostyle's named strings implementation:

https://github.com/vivliostyle/vivliostyle.js/tree/master/packages/core/test/files/named-strings

- [named-strings.html](https://raw.githack.com/vivliostyle/vivliostyle.js/master/packages/core/test/files/named-strings/named-strings.html) -- Named strings - string() function
  - [view with Vivliostyle](https://vivliostyle.org/viewer/#src=https://raw.githack.com/vivliostyle/vivliostyle.js/master/packages/core/test/files/named-strings/named-strings.html)
- [string-set-content.html](https://raw.githack.com/vivliostyle/vivliostyle.js/master/packages/core/test/files/named-strings/string-set-content.html) -- string-set with content() function
  - [view with Vivliostyle](https://vivliostyle.org/viewer/#src=https://raw.githack.com/vivliostyle/vivliostyle.js/master/packages/core/test/files/named-strings/string-set-content.html)
- [string-set-attr.html](https://raw.githack.com/vivliostyle/vivliostyle.js/master/packages/core/test/files/named-strings/string-set-attr.html) -- string-set with attr() function
  - [view with Vivliostyle](https://vivliostyle.org/viewer/#src=https://raw.githack.com/vivliostyle/vivliostyle.js/master/packages/core/test/files/named-strings/string-set-attr.html)

**Comment by zopyx** [comment]
will look into this

**Comment by zopyx** [comment]
I put the examples from your VS repo into my own incubator:

https://github.com/zopyx/print-css-rocks/tree/vivliostyle/lessons/in-progress/lesson-named-strings

https://github.com/zopyx/print-css-rocks/tree/vivliostyle/lessons/in-progress/lesson-set-attr

https://github.com/zopyx/print-css-rocks/tree/vivliostyle/lessons/in-progress/lesson-set-content

**Comment by zopyx** [comment]
@MurakamiShinyu what is your expectation regarding the correct headers for named-strings?

A-A
BAB
CCC

**Comment by zopyx** [comment]
The related lessons are now on beta.
