### ISSUE TITLE
CMYK support in pagedjs?

### ISSUE THREAD

**Issue by monobjorn** [zopyx/print-css-rocks#18]
It is stated that pagedjs has CMYK support on the page https://print-css.rocks/lesson/lesson-cmyk  
However the generated pdf does not seem to produce the correct output. From what I can see with my bare eye there are no background color on the top paragraph.
Should it be marked as not passing the test?

**Comment by zopyx** [comment]
How did you do the check?

**Comment by zopyx** [comment]
Possibly true. CMYK is perhaps a weak spot of print-css.rocks since I do not know much about CMYK and how to check it properly (I don't have access to Acrobat). Any idea?

**Comment by MurakamiShinyu** [comment]
A simple CMYK color checking is possible with [PressPDF](https://presspdf.com/).

Steps:
1. Upload the PDF file to https://presspdf.com/upload-file.php.
2. Click the "Pdf colorspace" tool button.
3. Check the "Pdf colorspace" info.

e.g., with Antennahouse output PDF:

<img width="1375" alt="Screen Shot 2022-08-16 at 18 31 58" src="https://user-images.githubusercontent.com/3324737/184850178-d72f1798-ed4e-455e-99dc-8640abfed54d.png">

<img width="1375" alt="Screen Shot 2022-08-16 at 18 32 12" src="https://user-images.githubusercontent.com/3324737/184850215-f7e58d4c-2f5d-480e-8b0a-478c57bfccc8.png">

The result, Images and Vector graphics are CMYK, and Font is both RGB and CMYK, shows AntennaHouse supports CMYK color as expected.

On the othar hand, with Pagedjs output PDF:

<img width="1331" alt="Screen Shot 2022-08-16 at 18 34 15" src="https://user-images.githubusercontent.com/3324737/184851033-6db06b6f-8b89-425f-b8b0-e9814a68c8f5.png">

The result, all Images, Vector graphics, and Font are RGB, shows Pagedjs does not support CMYK color.

**Comment by zopyx** [comment]
The CMYK lesson has been fixed.
