### ISSUE TITLE
Test fixes

### ISSUE THREAD

**Issue by faceless2** [zopyx/print-css-rocks#22]
Hi there - just running through your tests and I have a few comments:

lesson-cmyk
* the syntax from css-color-5 is (or will be) `device-cmyk(c m y k)`. I think it's fairly widely supported now, whereas the `cmyk(c,m,y,k)` is common but has never been standardised. Ref: https://www.w3.org/TR/css-color-5/#device-cmyk (it was in color-4 but got bumped to color-5)
 
lesson-css-transformations
* you've got `break-after: always`, I think you want `break-after: page`

lesson-fonts-emoji
* you're loading a @font-face with `font-family: Emoji`, but emoji is one of the generic font familes (Ref: https://www.w3.org/TR/css-fonts-4/#emoji-def) so this isn't going to work. To fix, either change it to `"Emoji"` (with quotes) both in the @font-face and the `font-family`, or pick literally almost any other word!

lesson-mathml-native
* you need a `<meta charset="utf-8">`, there are some UTF8 sequences in the document and the default encoding for HTML is ISO8859-1. Same for the mathml torture test and lesson-right-to-left.

lesson-set-content
* You've set the `FirstLetter` string to `content(first-letter)`, which is defined to be "_The first letter of the element, as defined for the [::first-letter](https://www.w3.org/TR/css3-selectors/#first-letter) pseudo-element_" (in css-gcpm-3), and the first letter pseudo-element is defined as "_If an element has [::before](https://www.w3.org/TR/css-pseudo-4/#selectordef-before) or [::after](https://www.w3.org/TR/css-pseudo-4/#selectordef-after) content, the ::first-letter applies to the first letter of the element **including** that content._" (in css-pseudo-4). Which makes the first letter on page 2 "C" from Chapter, not "M" from More.

Great tests otherwise, lots of nasty corner cases for us to debug - thanks.

**Comment by zopyx** [comment]
> lesson-css-transformations
> 
> * you've got `break-after: always`, I think you want `break-after: page`

No, i want a break after each test section. Anway, the behavior is as expected.

**Comment by zopyx** [comment]
> lesson-fonts-emoji
> 
> * you're loading a @font-face with `font-family: Emoji`, but emoji is one of the generic font familes (Ref: https://www.w3.org/TR/css-fonts-4/#emoji-def) so this isn't going to work. To fix, either change it to `"Emoji"` (with quotes) both in the @font-face and the `font-family`, or pick literally almost any other word!

Good catch...fixed

**Comment by zopyx** [comment]
> * you need a `<meta charset="utf-8">`, there are some UTF8 sequences in the document and the default encoding for HTML is ISO8859-1. Same for the mathml torture test and lesson-right-to-left.

Thanks, fixed. I would assume that all renderers use utf8 by default

**Comment by zopyx** [comment]
The remaining issues need further investigations when I have more time

**Comment by zopyx** [comment]
> * the syntax from css-color-5 is (or will be) `device-cmyk(c m y k)`. I think it's fairly widely supported now, whereas the `cmyk(c,m,y,k)` is common but has never been standardised. Ref: https://www.w3.org/TR/css-color-5/#device-cmyk (it was in color-4 but got bumped to color-5)

The CMYK test is clearly weak (because I don't know much about CYMK and don't know of any free tools for checking PDFs)

**Comment by faceless2** [comment]
> you've got break-after: always, I think you want break-after: page

The point I was making is that `break-after: always` is not valid CSS, so if you don't want the forced break you could just delete that rule. https://www.w3.org/TR/css-break-3/#break-between

**Comment by zopyx** [comment]
> The point I was making is that `break-after: always` is not valid CSS, so if you don't want the forced break you could just delete that rule. https://www.w3.org/TR/css-break-3/#break-between

I replace all `page-break-before|after` with its modern variant

**Comment by zopyx** [comment]
I think all issues are now resolved and addressed
