### ISSUE TITLE
What "minor rendering issues" on Mathml native test?

### ISSUE THREAD

**Issue by MurakamiShinyu** [zopyx/print-css-rocks#23]
In the latest beta MathML-native test results <https://beta.print-css.rocks/lesson/lesson-mathml-native>, only the AntennaHouse result is marked as OK (without issues):

<img width="476" alt="Screen Shot 2022-08-16 at 15 44 30" src="https://user-images.githubusercontent.com/3324737/184814686-0ee35515-c7da-4ce9-b7ac-6333b140ce44.png">

and the Vivliostyle result is marked as "OK with issues" with message "some minor rendering issues":

<img width="556" alt="Screen Shot 2022-08-16 at 15 47 01" src="https://user-images.githubusercontent.com/3324737/184815347-2d48c415-0729-4a20-877c-3060315ab823.png">

What are the "minor rendering issues"?

One difference between AntennaHouse and Vivliostyle results is the math box horizontal alignment. In the AntennaHouse result, the math box width is fit  to the math content, and in the Vivliostyle result, the math box width is 100% of the containing block width. I think the Vivliostyle result is correct because `display: block;` is specified on the `math` element and the block box has 100% of the containing block by default.

https://github.com/zopyx/print-css-rocks/blob/2a41a0e8fada2bcf451e0e403fa12b68a796987e/lessons/lesson-mathml-native/styles.css#L3-L9

**Comment by zopyx** [comment]
I changed it to OK
