### ISSUE TITLE
Image multi columns test has non-standard property "float: column-top next"

### ISSUE THREAD

**Issue by MurakamiShinyu** [zopyx/print-css-rocks#24]
The image multi columns test has CSS float property `float: column-top next`:

https://github.com/zopyx/print-css-rocks/blob/2cf6736d8b7c3e7999de6c52f740d4254d8d484d/lessons/lesson-image-multi-columns/styles.css#L18-L21

This float property value `column-top next` does not conform to the CSS Page Floats draft spec:
https://www.w3.org/TR/css-page-floats-3/#float-property

It seems that this non-standard float value is for Prince version <= 13: 
https://www.princexml.com/doc/13/styling/#conditional-modifiers

The current Prince version 14 has changed the extensions to floats:
https://www.princexml.com/doc/styling/#prince-extensions-to-floats

As a result, this non-standard float property (`float: column-top next`) does not work in the latest Prince. In the test results, Prince and other tools have almost same layout, except AntennaHouse that uses different stylesheet (with AH extension), but only Prince and AntennaHouse are marked as "OK": 

<img width="629" alt="Screen Shot 2022-08-16 at 16 17 54" src="https://user-images.githubusercontent.com/3324737/184820563-6757e2ad-563d-4b74-bc26-6b091dc66b0e.png">

I think that the non-standard float property should be removed from this Image multi columns test. The column-top float feature, e.g., `float-reference: column; float: top`, is defined in the CSS Page Floats draft spec but currently not well supported. If you want to test such advanced float feature, it should be in Advanced tests and not in Intro tests.

**Comment by zopyx** [comment]
Accepted. I moved the complete lesson out into the  `in-progress` folder and out of the public display.
