### ISSUE TITLE
lesson-set-attr: fix assumptions about margin in page at-rule

### ISSUE THREAD

**Issue by faceless2** [zopyx/print-css-rocks#25]
This test does not set the margin in the `@page`.

The default value is either 0 or not defined, depending on whether you think the default value for the margin _property_ (zero) is the same as the value for the margin _descriptor_ (as used in the page at-rule). Either way it various across renderers. Prince (for example) sets this to 72px but our BFO renderer sets it to 0, meaning if it's not set it will overlay the page content.

I'd suggest it should be initialized in this test:

```css
@page {
    margin: 72px
}
```

**Comment by zopyx** [comment]
I added the extra margin and corrected the result (not published online yet)
