### ISSUE TITLE
Update Vivliostyle -- Running elements are supported

### ISSUE THREAD

**Issue by MurakamiShinyu** [zopyx/print-css-rocks#30]
Vivliostyle now supports running elements (since Vivliostyle CLI [7.3.0 (2023-05-15)](https://github.com/vivliostyle/vivliostyle-cli/blob/main/CHANGELOG.md#730-2023-05-15)).

Please update to the latest version and update the Running elements test result. 

The "Current version" info in https://print-css.rocks/tools is outdated:

> - Current version:
>   - Vivliostyle CLI 5.9.0
>   - Vivliostyle.js 2.19.2

The current version is:
  - Vivliostyle CLI 8.0.1
  - Vivliostyle.js 2.25.2

**Comment by zopyx** [comment]
At the moment, I update only once per years due to the amount of time need for running re-evaluations.
So, no update before 2024

**Comment by zopyx** [comment]
Marked as OK in the current release
