### ISSUE TITLE
PagedJS should not be removed

### ISSUE THREAD

**Issue by MurakamiShinyu** [zopyx/print-css-rocks#31]
> - V 5.2 - June 2023 (removed PagedJS due to project inactivity, lack of communication etc.)

[PagedJS](https://github.com/pagedjs/pagedjs) does not seem to be inactive. The [commit history](https://github.com/pagedjs/pagedjs/commits/main) shows that there were 28 commits from beginning of this year. This number is not very large, but it is sufficient to show that the project is not inactive. Also the communication is not lacking as far as the [GitHub issues](https://github.com/pagedjs/pagedjs/issues) shows. Most issues have been replied by project members.

If you think Paged.js is not recommendable, it is better to explain why it is not recommendable than to remove it. Your site can help PagedJS users to find a better tool. If PagedJS is removed, PagedJS users hardly find your site. Note that PagedJS has large number of users and that is growing (see the npm trends https://npmtrends.com/pagedjs). They will want to get lessons from your site, and may want to find alternatives to PagedJS. Your site can help them.

Please reconsider your decision to remove PagedJS.

**Comment by zopyx** [comment]
To be re-evaluated for the next major release in 2024. For now, PagedJS remains outside for the reasons explained.
