### ISSUE TITLE
Time to include Blink as tool?

### ISSUE THREAD

**Issue by ppKrauss** [zopyx/print-css-rocks#33]
Hi, seems that is time to include [Blink](https://en.wikipedia.org/wiki/Blink_(browser_engine)) (and Chrome browser interface to "print with no footer") at  https://print-css.rocks/tools

-----

**See** https://test.csswg.org/harness/results/css-break-3_dev/grouped/ 
![image](https://github.com/zopyx/print-css-rocks/assets/1651447/842374d3-3d80-47c9-aa9e-a5792b1c1d9d)

and the [css-break-3](https://www.w3.org/TR/css-break-3/): we are waiting 10 years [since XSL-FO officially dead](https://stackoverflow.com/a/21345708/287948), now a "browser with standard HTML5 + main standard CSS + css-break-3" exists.

**Comment by zopyx** [comment]
Neither Chrome nor Blink support the W3C Paged Media standard.
