### ISSUE TITLE
paged.js?

### ISSUE THREAD

**Issue by Eric24** [zopyx/print-css-rocks#4]
Thank you for putting together this excellent site! I'm curious if you have plans to add paged.js as one of your "top level" PDF converters?

**Comment by zopyx** [comment]
Support for PagedJS and Typeset.sh is coming this fall...support is already available on the "typeset.sh" branch and I am already in contact with both teams for issues I found over the last months.

**Comment by ggrossetie** [comment]
Hello @zopyx and thanks for https://print-css.rocks/ it's a great resource!
I've noticed that Paged.js is missing from the "summary" table:

![summary-table-missing-pagedjs](https://user-images.githubusercontent.com/333276/92359790-1b593280-f0ec-11ea-819f-c4ded45859ce.png)

Also, it says "untested" even when the result seems to be the expected result, for instance on font:

![untested](https://user-images.githubusercontent.com/333276/92359837-2c09a880-f0ec-11ea-953e-4cc2c97ee7a9.png)

We also published a new version of Paged.js CLI using the latest release of Paged.js: https://www.npmjs.com/package/pagedjs-cli/v/0.1.1
Hopefully, some issues are now fixed :sweat_smile:

**Comment by zopyx** [comment]
I have support for PagedJS and Typeset.sh already in the making (actually finished) on a dedicated branch. I just need to go through all lessons and evalute the output...coming this fall

**Comment by ggrossetie** [comment]
Excellent, let me know if you need help 👍🏻

**Comment by zopyx** [comment]
The related branch is

https://github.com/zopyx/print-css-rocks/tree/typeset.sh

It contains already the PDFs for PagedJS and typeset.sh

An updated version of pagedjs-cli with the current state of the implementation would be appreciated. My feeling is that the pagedjs-cli is always lacking behind. Is there a reason why the PageJS implementation/release can not be kept automatically in sync?

**Comment by ggrossetie** [comment]
> An updated version of pagedjs-cli with the current state of the implementation would be appreciated. 

Ok.
You mean generate again the PDF and screenshots?
For now, I'm using the following procedure:

**Prerequisites:**

- install Paged.js CLI locally

**Generate**

For each lesson, execute `make pagejs`:

```
$ cd lessons/lesson-basic
$ make pagedjs
$ cd ../lessons/lesson-fonts
# ...
```

Is there a better way to generate all the lessons at once?

> My feeling is that the pagedjs-cli is always lacking behind. Is there a reason why the PageJS implementation/release can not be kept automatically in sync?

In my opinion, `pagedjs-cli` should not use a strict version of Paged.js.
So when a new (non-breaking) version of Paged.js is released, the CLI can be installed again/updated to use the latest version. The main benefit is that we don't have to release a new version of `pagedjs-cli` just to bump the version of `pagedjs`.
I will open an issue to suggest this change.

**Comment by zopyx** [comment]
Check the `generate.sh` script. With a little modification it might be used to run only the pagedjs conversions.

The PDFs however are already in the repo:

https://github.com/zopyx/print-css-rocks/tree/typeset.sh/lessons/generated

**Comment by zopyx** [comment]
PagedJS is now included
