### ISSUE TITLE
Using CSSWG cases?

### ISSUE THREAD

**Issue by ppKrauss** [zopyx/print-css-rocks#5]
The main browsers have been tested with the [CSSWG](https://en.wikipedia.org/wiki/CSS_Working_Group)'s test specifications of

   http://test.csswg.org/suites/css-break-3_dev/nightly-unstable/html/
   or  https://test.csswg.org/harness/test/css-break-3_dev/

Is there a way to list all equivalent or similar "test vs lesson" of  [print-css-rocks/lessons](https://github.com/zopyx/print-css-rocks/tree/master/lessons)?

**Comment by zopyx** [comment]
The current lessons and tests are (highly) opinionated.
It is a huge effort for testing and validating all tests for each release. 

Perhaps it would make sense to take the tests above and convert them automatically but without manual validation (there is really no way for automated validation of converted PDFs here)

**Comment by zopyx** [comment]
Closing this issue since I do not see any chance for automated testing and valuation of such a huge test suite
